spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  profiles:
    include: jwt